### ISSUE TITLE
How to check Windows 7 Professional MAK Key?

### ISSUE THREAD

**Issue by TGSAN** [casdr/mak-tool#1]
Hello, how can I using your program to check the Windows7 Professional MAK key ? I see PrivateKey But do not know if I can change here to check the different versions of the system Key ? And , where can I get the PrivateKey :)

**Comment by casdr** [comment]
I haven't tested it yet, but you should be able to get the activations by just using the product key of your Windows 7 license (Get-VamtProductKey) and the same private key.

**Comment by TGSAN** [comment]
Will the need for "pkeyconfig.xrm-ms" this file? Because I get the results of the operation are "None"

**Comment by casdr** [comment]
The key should be something like this:

```KeyId                : 12345-12345-123-123456-12-1234-1234.5678-1234567```

This should work just fine.

**Comment by casdr** [comment]
@TGSAN Can this be closed or are you still having issues?
