### ISSUE TITLE
InsecureRequestWarning: Unverified HTTPS request is being made.

### ISSUE THREAD

**Issue by DoomTay** [casdr/mak-tool#2]
I don't know if there's an outdated setting or if I'm supposed to input something other than the key exactly as it is

```ps
python mak.py AAAAA-BBBBB-CCCCC-DDDDD-EEEEE
C:\Users\IT Applicant\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
None
```

**Comment by casdr** [comment]
Hi,

Sorry for not replying to this sooner, I haven't seen this repository in a while. This is just a warning and shouldn't affect the output, probably the key is incorrect.

As this issue is more than a year old, I suspect you've either fixed it or found another solution, so I'll close this issue for now. If you however are still having trouble, you can reopen it :)

**Comment by pureair** [comment]
from https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings:

> Making unverified HTTPS requests is strongly discouraged, however, if you understand the risks and wish to disable these warnings, you can use [disable_warnings()](https://urllib3.readthedocs.io/en/latest/reference/urllib3.exceptions.html#urllib3.disable_warnings):
> 
> `import urllib3`
> `urllib3.disable_warnings()`
So the warning is not from Microsoft or the key validation service, and can be ignored.

To suppress the warning, open mak.py and edit as follows:

```
import requests
import sys
import urllib3   ### add this line
```

```
 def do_request(xmldata):
     urllib3.disable_warnings()   ###add this line, keep the space at the start
     url ="https://activation.sls.microsoft.com/BatchActivation/BatchActivation.asmx"
```
